### ISSUE TITLE
Should the linter work with squashed migrations?

### ISSUE THREAD

**Issue by drjeep** [3YOURMIND/django-migration-linter#107]
Are there any known issues around squashed migrations?

I'm getting the error below when running `lintmigrations` on any app with squashed migrations. For example `django-reversion` has the following squashed migration

```
reversion
 [X] 0001_squashed_0004_auto_20160611_1202 (4 squashed migrations)
```

and results in this error

```
Calling sqlmigrate command reversion 0001_initial
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django_migration_linter/management/commands/lintmigrations.py", line 148, in handle
    migrations_file_path=options["include_migrations_from"],
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django_migration_linter/migration_linter.py", line 110, in lint_all_migrations
    self.lint_migration(m)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django_migration_linter/migration_linter.py", line 134, in lint_migration
    sql_statements = self.get_sql(app_label, migration_name)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django_migration_linter/migration_linter.py", line 276, in get_sql
    stdout=dev_null,
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/commands/sqlmigrate.py", line 33, in execute
    return super(Command, self).execute(*args, **options)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/drjeep/workspace/health/hub/venv/lib/python2.7/site-packages/django/core/management/commands/sqlmigrate.py", line 61, in handle
    plan = [(executor.loader.graph.nodes[targets[0]], options['backwards'])]
KeyError: (u'reversion', u'0001_initial')
```

**Comment by David-Wobrock** [comment]
Hi @drjeep 
Thanks for opening an issue.
Can you tell me what version of Django you are running on?

The stack trace looks a lot like this Django bug report https://code.djangoproject.com/ticket/31318

On March 9th, a PR was merged (one I made hehe :P) to fix this bug.
https://github.com/django/django/pull/12518
It can be that one of the latest versions of Django contains the fix.

----

And since the migration linter heavily relies on the Django `sqlmigrate` command, it is buggy when the command is buggy

**Comment by drjeep** [comment]
I'm using Django 1.11.29

That's probably it, thank you (and for taking the time to fix Django :-)
