### ISSUE TITLE
Calling next() on empty array

### ISSUE THREAD

**Issue by mes3yd** [3YOURMIND/django-migration-linter#19]
```
======================================================================
ERROR: test_latest_migrations (apps.b3_core.tests.test_migrations.MigrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "/home/melvyn/.local/py-env/django-ECigcvew/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 102, in lint_all_migrations
    self.lint_migration(*m)
  File "/home/melvyn/.local/py-env/django-ECigcvew/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 69, in lint_migration
    sql_statements)
  File "/home/melvyn/.local/py-env/django-ECigcvew/lib/python3.6/site-packages/django_migration_linter/sql_analyser.py", line 72, in analyse_sql_statements
    if test['fn'](statement, errors=errors):
  File "/home/melvyn/.local/py-env/django-ECigcvew/lib/python3.6/site-packages/django_migration_linter/sql_analyser.py", line 24, in has_default
    for err in kwargs['errors']
StopIteration

----------------------------------------------------------------------
Ran 1 test in 10.889
```
Because next() is called on an array with no elements (none match the if statement in the generator).

**Comment by David-Wobrock** [comment]
Hi @mes3yd, thank you for reporting this issue.

I just released a small patch to fix this. However, I didn't add a test that reproduces this error.
If you want to add one, I'd be pleased to review your PR :) (even if the tests in this library are not well written and can be difficult to get in).

Cheers,
David
