### ISSUE TITLE
Cache does not work if apps are not located in a subfolder

### ISSUE THREAD

**Issue by flixx** [3YOURMIND/django-migration-linter#32]
Our apps live in a subfolder called `apps/`. When I execute the linter I get this:
```
Traceback (most recent call last):
  File "/var/www/django/apps/b3_core/tests/test_migrations.py", line 39, in test_latest_migrations
    linter.lint_all_migrations()
  File "/usr/local/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 149, in lint_all_migrations
    self.lint_migration(*m)
  File "/usr/local/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 79, in lint_migration
    md5hash = self.old_cache.md5(app_name, migration_name)
  File "/usr/local/lib/python3.6/site-packages/django_migration_linter/cache.py", line 48, in md5
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/django/voucher/migrations/0001_initial.py'
```
Probably we would need a better way to get the actual migration file for hashing. Ideas?

**Comment by flixx** [comment]
@David-Wobrock We already have the full path to the migration in `_gather_all_migrations`. Do you think it is fine to return that path and pass it to `lint_migration()`. That would change the signature of `lint_migration()` in a backward incompatible way though.

**Comment by David-Wobrock** [comment]
@flixx I think it is okay to change the signature of the `lint_migration`
I'm working on introducing a `Migration` object that will hold information of the full path, the app name, the migration name, etc.
