### ISSUE TITLE
don't assume git_root is the django_path

### ISSUE THREAD

**Issue by linuxmaniac** [3YOURMIND/django-migration-linter#37]
My django project is allocated in a subdirectory of a git repo like: ``xpbx/xpbx`` so after c6df7e53a0abd0e74b7dfa107c0dbb6de474f5ff I get this error:
```
DJANGO_SETTINGS_MODULE=xpbx.test django-migration-linter --no-cache $(pwd)/xpbx origin/2.4.1
(customers, 0010_auto_20181026_1330)... Traceback (most recent call last):
  File "/home/vseva/Env/xpbx/bin/django-migration-linter", line 11, in <module>
    sys.exit(_main())
  File "/home/vseva/Env/xpbx/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 341, in _main
    linter.lint_all_migrations(git_commit_id=args.commit_id)
  File "/home/vseva/Env/xpbx/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 145, in lint_all_migrations
    self.lint_migration(m)
  File "/home/vseva/Env/xpbx/lib/python3.6/site-packages/django_migration_linter/migration_linter.py", line 81, in lint_migration
    md5hash = self.old_cache.md5(migration.abs_path)
  File "/home/vseva/Env/xpbx/lib/python3.6/site-packages/django_migration_linter/cache.py", line 47, in md5
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vseva/Foehn/xpbx/xpbx/xpbx/customers/migrations/0010_auto_20181026_1330.py'
```

**Comment by flixx** [comment]
@linuxmaniac Thanks for the PR :)
Is #39 also fixing your issue?

**Comment by David-Wobrock** [comment]
Hi @linuxmaniac 
Thanks a lot for the PR. I'm reopening this to be sure that your issue is fixed.

Can you test your project with the latest version of the linter that lives on `master` currently.
If it is not fixed, could you describe your issue a bit more precisely so we can work on it :)
Cheers,
David
